image: maven:3-openjdk-17

cache:
  paths:
    - .m2/repository

.verify:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

verify:jdk17:
  extends:
    - .verify

stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_DB: lizzard
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pt12345

build:
  stage: build
  script:
    - "cd backend"
    - "mvn clean package"
    - "cd .."

test:
  stage: test
  script:
    - "cd backend"
    - "mvn test"
    - "cd .."

deploy:
  stage: deploy
  script:
    - docker-compose up -d
