stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  POSTGRES_DB: lizzard
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pt12345

before_script:
  - chmod +x mvnw

build:
  stage: build
  script:
    - "cd backend"
    - "mvnw clean package"
    - "cd .."

test:
  stage: test
  script:
    - "cd backend"
    - "mvnw test"
    - "cd .."

deploy:
  stage: deploy
  script:
    - docker-compose up -d
